### ISSUE TITLE
Naming conflict with components

### ISSUE THREAD

**Issue by harry-sm** [jacobwgillespie/styled-icons#170]
Hello, 
An issue I have experience using this lib is naming conflicts between my project components and styled-icons. Example
`import { Home } from 'styled-icons/material';`

I already have a component called `Home`. It would be nice with styled-icons had unique names. To solve this I currently do `import { Home as SiHome } from 'styled-icons/material';` not the best naming convention but it gets the job done. One strategy I have seen font-awesome use is
```tsx
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
import { faHome } from '@fortawesome/fontawesome-free-solid';

<FontAwesomeIcon icon={faHome} />
```
This ensures that there will almost never be a naming conflict. While this is a great strategy this would require an API change, and its a little more verbose than styled-icons. Maybe, it could be considered for a future version or some other solution.

**Comment by jacobwgillespie** [comment]
Yeah, the decision to preserve the original icon names rather than prefix them was intentional, as then the names of the components are the names of the icons.  I've always found it a little annoying when using icons packs if the pack has some sort of custom naming scheme basically.

That said, it does create the issue of name conflicts, like where the icon names match the names of components you defined, or if you want to import the same icon from the regular pack and the solid pack, for instance.  But I wanted to avoid `FaSolidHome` and `FaRegularHome`, etc.

Two ideas for how to handle this:

First, you could do what you mentioned and alias the imports:

```typescript
import {Home as HomeIcon} from 'styled-icons/material'

<HomeIcon />
```

Second, you can also potentially use ES modules imports to alias the whole pack:

```typescript
import * as material from 'styled-icons/material'

<material.Home />
```

The only concern there is if you don't have your bundler configured correctly, you can accidentally bundle _all_ the icons rather than just the ones you're using.  If everything's working as expected though, the `* as name` import should properly tree-shake down to just the icons you're using.  And then you don't have to alias icon names:

```typescript
import * as regular from 'styled-icons/fa-regular'
import * as solid from 'styled-icons/fa-solid'

const HomeIcon = selected ? solid.Home : regular.Home

<HomeIcon />
```

**Comment by harry-sm** [comment]
So I use CRA and I never want to eject, not sure what the bundler config is in it.

I have been playing around with alternative solutions.

Options 1
```tsx 
import { material } from 'styled-icons';
type IconName = keyof typeof material;

export const MaterialIcons = ({name, ...props}: { name: IconName, size: number}) => {
	const Icon = material[name];
	if (Icon) {
		return (<Icon {...props} />);
	} else {
		return (<span>Icon Not Found</span>);
	}
};
```
Example usage:
```tsx
<MaterialIcons name="Home" size={20}/> Home
```
![image](https://user-images.githubusercontent.com/15040197/41997120-11565352-7a25-11e8-9817-e5c84928663d.png)

Pros:
- Icons in pack names remain the same.
- As of TS v2.9.*, which is in vscode v1.24, we get IntelliSense for literal types
- You can have a specific interface and component for each icon pack, eg. material icons or https://github.com/webkul/vivid supports a two-tone option font-awesome doesn't.

Cons:
- Tree shaking unknown

Option 2

```tsx 
type IconName = keyof typeof material;

type StyledIconsProps = { type: 'material', name: IconName, size: number};

export class StyledIcons extends React.Component<StyledIconsProps, {Icon: any}> {
	public state = {
		Icon: undefined
	};
	constructor(props: any) {
		super(props);
	}
	public componentDidMount() {
		const { type, name } = this.props;

		import(`styled-icons/${type}/${name}`).then(mod => {
			this.setState({Icon: mod[name]});
		}).catch(() => {
			this.setState({Icon: undefined});
		});
	}

	public render () {
		const { Icon } = this.state as any;
		const { type, name, ...props } = this.props;
		if (Icon) {
			return (
				<Icon {...props} />
			);
		}
		return (<span>Icon Not Found</span>);
	}
}
```
Example usage:
```tsx
<StyledIcons type="material" name="Home" size={20} />
```
Pros:
- Code splitting with dynamic imports
- A single component handles the icon imports

Cons:
- A single Interface, (props options are shown even when the icon pack doesn't support them)
- Typescript refuses to compile with the presence of dynamic imports (for me that is)

Here is a sandbox of both solutions https://codesandbox.io/embed/k9j35995yv

I also had an idea for a render prop solution but still fuzzy and might be overkill.
```tsx
<StyledIcons type="material" name="Home" render{(Home) => <Home size={20} />} />
```

**Comment by jacobwgillespie** [comment]
I also use Create React App, so most tree shaking scenarios should already work correctly.  Specifically, this should tree-shake:

```typescript
import * as material from 'styled-icons/material'

const HomeIcon = material.Home

<HomeIcon />
```

I've tried to do something similar where you create a wrapper component, and it _almost_ tree-shakes, but from my testing, Webpack can get confused when re-exporting and end up bundling everything.

In one project, I have two files, `Icon.tsx` and `supportedIcons.tsx`.

**supportedIcons.tsx:**

```typescript
export {Home} from 'styled-icons/material/Home'
export {Circle} from 'styled-icons/fa-solid/Circle'
```

**Icon.tsx:**

```typescript
import React from 'react'
import {StyledIconProps} from 'styled-icons'
import * as supportedIcons from './supportedIcons'

export type IconName = keyof typeof supportedIcons

interface Props extends StyledIconProps<any> {
  name: IconName,
}

export const Icon: React.SFC<Props> = ({name, ...other}) => {
  const StyledIcon = supportedIcons[name]
  return <StyledIcon {...other} />
}
```

Then you can use `<Icon name="Home" />` and that name prop is type-checked.

In your second example with dynamic imports, that should also work, but it looks like CodeSandbox is not using TypeScript 2.9 which is why it won't compile (you need TS 2.9 and you need `"module": "esnext"` in the tsconfig.json).

**Comment by harry-sm** [comment]
Yeah using dynamic requires additional configuration. I don't know the inner workings of how tree shaking works maybe I should look into it.

**Comment by jacobwgillespie** [comment]
I'm going to mark this as closed - do feel free to open another issue if anything else comes up!

**Comment by harry-sm** [comment]
Yeah cool.
