### ISSUE TITLE
Using styled-icons with NextJS

### ISSUE THREAD

**Issue by fillipvt** [jacobwgillespie/styled-icons#272]
Hello!

Tried setting `styled-icons` with next.js following first their [`styled-components` example](https://repl.it/@fillipvt/nextjs-with-styled-components-and-styled-icons). Then I just imported `styled-icons` and then the icon I want to use from FontAwesome.

This is the result, basically an error:

```
Unexpected token export
/home/runner/node_modules/styled-icons/fa-solid/index.js:1
(function (exports, require, module, __filename, __dirname) { export { AddressBook } from './AddressBook';
```

Here's the resulting error:

https://repl.it/@fillipvt/nextjs-with-styled-components-and-styled-icons

I'm not sure what's going on and was hoping perhaps here I could find some guidance.

Thanks

**Comment by jacobwgillespie** [comment]
Hey @fillipvt,

The problem is that `styled-icons` uses the ES modules `import` and `export` in the npm package files themselves, as this allows JavaScript bundlers to apply tree-shaking and remove unused code.  That's really important for this package because otherwise you'd end up bundling all of the icons in your resulting JS bundle, which can be quite large (several megabytes).

That requires that the JS bundler be configured to understand ES modules, which practically speaking means that if the bundler is using Webpack, like Next is, then it needs to be using Webpack 4.  The version of Next that you're using is powered by Webpack 3, which is why you're getting the error.

Next switched to Webpack 4 in version `6.1.1-canary.3`, but it looks like there hasn't been a stable release of that version yet.  Once the next stable version of Next is released, `styled-icons` should just work.

In the meantime, there are CommonJS exports available that don't use ES module syntax and should work just fine with your app now.  The only trick is you should import icons directly, rather than importing a whole pack, to avoid bundling all of the icons:

```typescript
import React from "react";
import styled from "styled-components";
import BalanceScale from "styled-icons/fa-solid/BalanceScale.cjs";

const GreenBalanceScale = styled(BalanceScale)`
  color: green;
`;
```

You can add `.cjs` to any of the icon imports to get that CommonJS version.

**Comment by fillipvt** [comment]
Thank you very much @jacobwgillespie ! This looks awesome: 

https://repl.it/@fillipvt/nextjs-with-styled-components-and-styled-icons

I have one last question. How do you normally manage dynamic sizes for icons? Let's say one wants to have the icon's size change according to the viewport.

```js
import React from "react";
import styled from "styled-components";
import { Rocket } from "styled-icons/fa-solid/Rocket.cjs";

const OrangeRocket = styled(Rocket).attrs({
  size: "70"
})`
  color: orange;
`;
```

I'm using here `.attrs({})` to pass down the size, but I'm not certain how to change this according, for example, to the window.width. Any ideas? All is appreaciated! Thank you again

**Comment by jacobwgillespie** [comment]
Awesome!  Couple of ideas for dynamic sizes:

You have the Styled Components API available, so you can pass a function instead of a value and it should resolve:

```typescript
const OrangeRocket = styled(Rocket).attrs({
  size: () => window.innerWidth * 0.25
})`
  color: orange;
`;
```

However I don't think that'll update if/when the window is resized.  For that behavior, you could either find a component that supports listening to window resize events, or probably better, just use CSS:

```typescript
const OrangeRocket = styled(Rocket)`
  color: orange;
  width: 25vw;
  height: 25vw;
`;
```

That would set the width to 25% of the viewport width and it would dynamically resize with the browser without extra work.  Then you could add breakpoints in the CSS, you could use CSS `calc()` if you needed to do any more fancy rules and didn't need to support IE9, etc.

Just ignoring the `size` attribute and setting the CSS `width` / `height` is probably what I'd do.

**Comment by jacobwgillespie** [comment]
Cool, happy to help 👍

**Comment by ellsclytn** [comment]
Given Next is now using Webpack 4, I think this issue might be valid again:

I've been unable to use styled-icons via the ES Module import, even though we're now up to Next v7 (getting the `Unexpected token *` issue). I have an example that demonstrates the issue here: https://github.com/ellsclytn/next-styled-icons

**Comment by jacobwgillespie** [comment]
@ellsclytn thanks for the reproduction - I was able to find a potential fix.  Let me get it cleaned up and I'll post back once it's ready.

**Comment by jacobwgillespie** [comment]
@ellsclytn Okay, I created a new NPM package `next-plugin-styled-components`, which you can add to your `next.config.js` file to enable tree shaking with Styled Icons in a Next app.  Using it looks roughly like this:

```javascript
const withStyledIcons = require('next-plugin-styled-icons')

module.exports = withStyledIcons()
```

Or with another plugin already in there:

```javascript
const withStyledIcons = require('next-plugin-styled-icons')
const withTypeScript = require('@zeit/next-typescript')

module.exports = withTypeScript(withStyledIcons())
```

Or with custom config:

```javascript
const withStyledIcons = require('next-plugin-styled-icons')

module.exports = withStyledIcons({
  ...customConfigHere,
})
```

There's more info in [the README](https://github.com/jacobwgillespie/styled-icons/tree/master/packages/next-plugin-styled-icons).

Can you let me know if it works for you?  It seems to work for for me in your sample app.

**Comment by ellsclytn** [comment]
Works perfectly! Thanks for getting on this so quickly 😄

**Comment by jacobwgillespie** [comment]
Awesome, happy to hear!
