### ISSUE TITLE
Typescript "css" prop missing

### ISSUE THREAD

**Issue by zenVentzi** [jacobwgillespie/styled-icons#644]
> Property 'css' does not exist on type 'IntrinsicAttributes & Pick<StyledIconProps, "string" | "style"

For example, in js I have the following code, working just fine:
```

<FacebookLogo
        size="2em"
        css="cursor: pointer"
        onClick={() => console.log('click')}
      />
```

now rewriting in TS, I get the error that css prop does not exist. Does it not? Now I'm with the latest version of styled-icons, before I used to be with 2.something. Are there any changes or just the type is missing?

**Comment by jacobwgillespie** [comment]
Hey, so that's an implementation detail of Styled Components's TypeScript types.  They have intentionally left out the `css` prop from the types as otherwise just having `styled-components` anywhere in your dependencies would add that type to every React component, which might not be what you intend (since you need the Babel plugin running for that prop to work).

You can opt-in to that type via some instructions in the type definition file:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/abe95f396c22948fec0aa9e393d3916d04e485be/types/styled-components/index.d.ts#L484-L513:

```typescript
/**
 * The CSS prop is not declared by default in the types as it would cause 'css' to be present
 * on the types of anything that uses styled-components indirectly, even if they do not use the
 * babel plugin.
 *
 * You can load a default declaration by using writing this special import from
 * a typescript file. This module does not exist in reality, which is why the {} is important:
 *
 * ```ts
 * import {} from 'styled-components/cssprop'
 * ```
 *
 * Or you can declare your own module augmentation, which allows you to specify the type of Theme:
 *
 * ```ts
 * import { CSSProp } from 'styled-components'
 *
 * interface MyTheme {}
 *
 * declare module 'react' {
 *   interface Attributes {
 *     css?: CSSProp<MyTheme>
 *   }
 * }
 * ```
 */
// ONLY string literals and inline invocations of css`` are supported, anything else crashes the plugin
export type CSSProp<T = AnyIfEmpty<DefaultTheme>> =
    | string
    | FlattenInterpolation<ThemeProps<T>>;
```

I'm going to close this issue, as I believe if you follow the directions above, it should work, but definitely let me know if it doesn't for whatever reason.

**Comment by zenVentzi** [comment]
In case somebody else stumbles upon this issue and the above doesn't work out of the box, check out [this ](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31245)thread. Basically for me I had to use `import * as types from 'styled-components/cssprop'` [because ](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31245#issuecomment-463640878)of babel 7 with typescript & webpack.
