### ISSUE TITLE
Is there any way to use icons with a <i> or <img> tag instead of the <svg> tag?

### ISSUE THREAD

**Issue by leworking** [jacobwgillespie/styled-icons#657]
I find difficult to style the imported icons, mainly referring to the dimensions, "white" space around the icon, etc. Perhaps an easier way would be to use the icons within an `<i>` or `<img>` tag.

Is this possible?

**Comment by jacobwgillespie** [comment]
Possibly - depending on what you're trying to accomplish.  You can always wrap Styled Icons in your own custom component and thus surround the SVG tag with something else:

```typescript
import React from 'react'

const IconWrapper = ({icon}) => <i>{icon}</i>

// or with TypeScript / types

import React from 'react'
import {StyledIcon} from 'styled-icons/types'

interface Props {
  icon: StyledIcon
}

const IconWrapper: React.FC<Props> = ({icon}) => <i>{icon}</i>
```

Then you can do something like:

```typescript
import {Person} from 'styled-icons/material'

const App = () => (
  <IconWrapper icon={Person} />
)
```

If you'd like to instead _replace_ the SVG tag with something else, that's likely not possible here, since this library's goal is to provide SVGs as React/Styled components.

You may have seen something like `<i className="fa-person"></i>` elsewhere, and that's typically used with a font-based icon delivery system.  There are workarounds, but the downside there is it's harder to ship only the icons that your app is using, vs everything inside the single font file.  But regardless, `styled-icons` doesn't ship with font-based icons.

For the `<img>` tag, you'd likely need access to the "real" SVG markup so that you could use it as a data-uri inside the `src` attribute, and Styled Icons are React components, so they can't fit inside an HTML attribute.  I'm hoping someday to create a new NPM library that contains just the SVGs of icons and then use that package as the data source for `styled-icons`, and with that you could potentially embed SVGs as data URIs.  But regardless, if you're looking to do that today, then you'll want a different icon library.

Let me know if I've misunderstood what you're trying to do here or if anything was confusing!

**Comment by leworking** [comment]
Thanks, a great explanation :) 

My motivation was that the only way to adapt some `svg` icons was through `viewbox`, and that cannot be modified through `css`. One possibility was to build the svg tag somehow, or to change the tag altogether (and then the question).

At the end though this is too overkill, and I'll just stick to icons that don't have this extra-space around.

**Comment by jacobwgillespie** [comment]
Oh interesting, @leworking do you have any examples or code snippets that produce that issue?  If there's something wrong with the icons themselves like extra space, it's possible I may be able to fix that in the icon preprocessor here.

**Comment by leworking** [comment]
It was just importing an arrow icon that I liked, and then I couldn't style it well enough. It had a significant padding around it, as if it was a bitmap with real blank space, not cropped.

Then I realized it wasn't one of the FontAwesome free icons (don't remember which was though), and I tried one of those and it didn't have that padding, so problem solved. Before that, I saw that I could modify viewBox to sort of crop the icon. Too hacky and inconsistent, however.

So far I've been using FA icons and all of them seem to be free from blank space. It is also possible that if you work with big spaces, this is not an issue for you. In my case I wanted the icon to fit in a small space, so it mattered to me.

*I'd say if the source icon is not good enough, then it is a problem of the icon, not of `styled-icons`
