### ISSUE TITLE
Tree Shaking isn't working

### ISSUE THREAD

**Issue by stramel** [jacobwgillespie/styled-icons#814]
We are using `styled-icons/material` with TypeScript in our CRA v3 app and when running `source-map-explorer` it is revealing that the entire `material` icon pack is being included in our production build.

For now we are working around by doing an import per icon which reduced our bundle size by ~600KB. Would love to be able to import from the icon pack level.

**Comment by jacobwgillespie** [comment]
Thanks for this catch!  I'm not sure if this is something that was broken by me in `styled-icons` at some point a while ago, or if perhaps the latest Create React App picks up some Webpack updates that caused this situation.

Either way, I've fixed by marking everything with `styled-icons` as side-effect free, so Webpack / CRA v3 will now properly tree-shake.

It's building now and will release in a moment as v7.15.1. 🎉

**Comment by stramel** [comment]
@jacobwgillespie Thanks for the quick fix! I just verified on the project I noticed it on and v7.15.1 does fix it!
