### ISSUE TITLE
styled-icons/feather/ArrowUpCircle and down arrow = blank

### ISSUE THREAD

**Issue by donaldboulton** [jacobwgillespie/styled-icons#945]
styled-icons/feather/ArrowUpCircle and styled-icons/feather/ArrowDownCircle is missing the arrow its just a blank circle

**Comment by lennartbuit** [comment]
I made an issue (#944) yesterday to indicate that they weren't showing up.I think that the fix was not sufficient, many icons are now unlike the ones on the feather website.

For example:
- https://styled-icons.js.org/?s=feather%20activity vs https://feathericons.com/?query=activity
- https://styled-icons.js.org/?s=feather%20clipboard vs https://feathericons.com/?query=clipboard

Hope this helps!

**Comment by jacobwgillespie** [comment]
@stramel, do you have any insight into this?  I believe the detection around removing `fill="none"` from #938 might be interfering with the `feather` icons.

I'll try to take a look at this shortly, in the meantime any PRs (from anyone) are welcome!

**Comment by stramel** [comment]
Oh, hmmm... I can take a look here shortly as well. Sorry for the inconvenience

**Comment by stramel** [comment]
So my changes shouldn't be removing the `fill="none"` but I think that's just getting overwritten by `currentColor`. Looking into preserving `currentColor` and `none` if specified on `fill`.

**Comment by stramel** [comment]
Not entirely sure how it was functioning before but I should have a fix out shortly. Doing some testing now.

**Comment by jacobwgillespie** [comment]
This will be released as v8.4.2 shortly - thank you @stramel! 🎉

**Comment by stramel** [comment]
You're very welcome! Sorry for breaking an icon pack 😅
